apiVersion: v1
kind: ServiceAccount
metadata:
  name: finetune-sa
  namespace: finetune
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/llmplatform-dev-finetune-api-irsa"
