apiVersion: v1
kind: Service
metadata:
  name: finetune-api
  namespace: finetune
  labels:
    app: finetune-api
spec:
  type: ClusterIP
  selector:
    app: finetune-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
