apiVersion: v1
kind: Service
metadata:
  name: eval-api
  namespace: eval
  labels:
    app: eval-api
spec:
  type: ClusterIP
  selector:
    app: eval-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
