apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-baseline
resources:
  - hf-token-secret.yaml
  - vllm-deployment.yaml
  - vllm-service.yaml
  - vllm-awq-deployment.yaml
  - vllm-fp16-deployment.yaml
  - vllm-lora-deployment.yaml
  - vllm-judge-deployment.yaml
