apiVersion: v1
kind: Service
metadata:
  name: mistral-7b-baseline
  namespace: llm-baseline
  labels:
    app: mistral-7b-instruct-vllm
spec:
  selector:
    app: mistral-7b-instruct-vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
