apiVersion: v1
kind: Service
metadata:
  name: data-engine
  namespace: platform
spec:
  selector:
    app: data-engine
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
