apiVersion: v1
kind: Service
metadata:
  name: quant-api
  namespace: quant
  labels:
    app: quant-api
spec:
  type: ClusterIP
  selector:
    app: quant-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
